name: PRUEBA 12PM
on:
  schedule:
    - cron: '20 16 * * *'
  workflow_dispatch:

jobs:
  test_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar sincronizacion automatica
        run: |
          curl -X GET "https://rockmell-system-default-rtdb.firebaseio.com/RATES.json" > rates.json
          curl -X PUT "https://rockmell-system-default-rtdb.firebaseio.com/DATA_TASAS.json" -d @rates.json