name: ROBOT TEST MANUAL 3 TIROS
on:
  workflow_dispatch:
jobs:
  raspar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Codigo
        uses: actions/checkout@v4
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Instalar Librerias
        run: npm install cheerio
      - name: Ejecutar Robot
        run: node --no-warnings index-forzado.js
        run: node --no-warnings index-forzado.js