name: Test Metodo Extra TZ

on:
  schedule:
    - cron: '0 16 * * 1-5' # 12:00 PM de Venezuela según la lógica común
  workflow_dispatch:

jobs:
  ejecutar-extra:
    runs-on: ubuntu-latest
    env:
      TZ: America/Caracas # Aplicando la variable de entorno solicitada
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install
      - run: node test.js metodo_extra